### ISSUE TITLE
Nodejs Version of jumpcutter

### ISSUE THREAD

**Issue by matefs** [WofWca/jumpcutter#11]
The extension helped me a lot. So i want to request you a nodejs version of this, that can run on terminal with local vídeos. Thank you WofWca.

**Comment by WofWca** [comment]
Glad to help.
Onto your issue – what's the end goal of that? Being able to watch local videos? If so, here's the issue for that #5, a few workarounds are described there. Otherwise please clarify.

**Comment by matefs** [comment]
I need a way that i can record into a file, the altered version of the vídeo. So, your script works very well, but i need upload this "compacted" video to a platform like youtube, facebook...
Thank you for your attention

**Comment by WofWca** [comment]
This is precisely what this extension is designed NOT to do :)
It was inspired by its command-line version, better versions of which you can find [here](https://github.com/carykh/jumpcutter/issues/180#issue-619582754).
