### ISSUE TITLE
Control panel flash when fast forward in local play mode.

### ISSUE THREAD

**Issue by lowwor** [WofWca/jumpcutter#154]
In play local file mode, the player's control panel would show and hide when fast-forward trigger which is annoying, would be better to hide it using something like the bottom code.
```
   videoEl.addEventListener('mouseover', async () => {
      videoEl.controls = true
    });
    videoEl.addEventListener('mouseout', async () => {
      videoEl.controls = false
    });
```

**Comment by WofWca** [comment]
Duplicate of #117
