### ISSUE TITLE
Make bookmarklet/webpage for android users

### ISSUE THREAD

**Issue by heartlog** [WofWca/jumpcutter#161]
So, it can also be used on smartphones without using any browser.
it's ok if it doesn't have interactive UI, only something like Jumpcutter local player(is enough).
With HTML, CSS, JS and jQ maybe?
I tried making it but it turns out to be a mess.
or at least help is appreciated.

**Comment by WofWca** [comment]
Hey! Thanks for reaching out!

I agree that UX of getting the extension to work on mobile is horrible. I don't actually even recall if I wrote any proper docs on how to install it on the Kiwi browser or how to install it in Firefox Nightly.

I'm not as familiar with smartphones as I should be, so bear with me. First let's make it clear that it's definitely gonna work without any browser whatsoever, a browser engine is absolutely necessary. Perhaps what I think you meant is an "add to home screen" feature that is applicable to websites. We could try to make it possible for the local file player of the extension. In Kiwi browser you can add the local file player to the home screen, but when I tap on it, nothing happens for me. In Firefox you can also add it to the home screen, with a hack described in https://github.com/WofWca/jumpcutter/issues/150, but it also won't open for me, idk.

If it's not about "add to home screen", then I think a native Android app utilizing WebView or GeckoView could also be an option, given how hard it is currently to install the extension on Chromium and Gecko browsers for Android. But I'm not sure if extensions can work in WebView or GeckoView, sounds unlikely. If that's the case, then #54 is necessary to implement (i.e. get rid of / make optional all the `browser` (Web Extensions API) usage.

Related: #65.

**Comment by WofWca** [comment]
So, we added support for Firefox for Android.
I think let's close this in favor of #54 now.
If you don't like either, please clarify a better approach and let's reopen / create another issue.
