### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sakurakitttens** [WofWca/jumpcutter#178]
There are still some silent parts, even with Jump Cutter enabled.
Maybe you could add some presets and some other settings that can help skip the silent parts entirely

**Comment by WofWca** [comment]
Hey!
Do you have the "experimental algorithm" enabled?
Could you clarify where that happens? Maybe show a screenshot or screen recording?
Because I'm not quite sure if I understand what exactly you mean.

**Comment by sakurakitttens** [comment]
There's too much distortion going on and there are still too many silent
parts. I wish there were some presets,where there is no distortion.

**Comment by WofWca** [comment]
To get rid of distortion, try setting "Margin before" to 0. To shorten the "grace period", set "margin after" to 0 as well.

**Comment by WofWca** [comment]
OK, the new "simple mode" #180 can be considered a "preset". Otherwise, with advanced settings enabled, all needed options can be controlled.

Please reopen if you have a more concrete suggestion.
