### ISSUE TITLE
Clicking the extension's icon gives me an empty box (latest Firefox and Waterfox)

### ISSUE THREAD

**Issue by Adulau2003** [WofWca/jumpcutter#184]
On FF 132.0.1, on Waterfox 6.5.1 (and 6.5.0). The extension used to work just fine before. But now the box is no longer showing.
When going to the "/options/index.html" page. I get the following visual:
https://files.catbox.moe/8v41mf.png

**Comment by WofWca** [comment]
Hmm looks bad indeed. Maybe the storage got corrupted somehow? Could you please open dev tools on the options page and see if there are any errors in the console?

**Comment by Adulau2003** [comment]
Ah, it has to do with the setting "privacy.resistFingerprinting" When set to False your add-on works. When set to True it breaks on modern FF and the latest Waterfox (Which is based on FF ESR 128) as of 6.5.0). Do with this info what you want. I just decided to turn off that setting. This isn't a particular fault of the add-on.

**Comment by Adulau2003** [comment]
Ah, it has to do with the setting "privacy.resistFingerprinting" When set to False your add-on works. When set to True it breaks on modern FF and the latest Waterfox (Which is based on FF ESR 128) as of 6.5.0). Do with this info what you want. I just decided to turn off that setting. This isn't a particular fault of the add-on.

**Comment by WofWca** [comment]
OK, thanks for the update!

However, I am still unable to reproduce, on Firefox 132.0.1 and on 134.0a1, even with `privacy.resistFingerprinting` enabled. Yes, I tried restarting the browser.

**Comment by Adulau2003** [comment]
Don't know what to tell you. But that fixed it for me. I can no longer reproduce it either :)
