### ISSUE TITLE
UI Text same as background color 

### ISSUE THREAD

**Issue by Rajdave69** [WofWca/jumpcutter#187]
![{9E94433C-EEC0-4E2A-AFCE-C269B8CE4B13}](https://github.com/user-attachments/assets/ee0c3281-0073-4f1c-acff-fedeca0a9391)

I have no idea how this happened but the background is white and so is the text

**Comment by Rajdave69** [comment]
Opera GX LVL 6 (core: 114.0.5282.159)
OS Windows 11 Version10.0.22631 Build 22631

Despite the browser having force dark mode, having that turned off doesn't affect this.
And force dark mode doesn't affect any other extension's page or popup

**Comment by WofWca** [comment]
Thanks!

We use default browser dark mode styles, there used to be a similar bug in Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1744749

A quick fix for us would be to apply styles explicitly instead, but I'd rather report it to whoever is responsible. I'll take care of it. Or, if you want to, let me know.

**Comment by Rajdave69** [comment]
![{1F2D492D-3EF0-4F61-971E-FEF3E83004D3}](https://github.com/user-attachments/assets/d6cbfd31-e0e8-4433-baba-d683f4b5a6dd)

Looks like it's fixed for the latest version of Opera GX

**Comment by WofWca** [comment]
Alright then, thank you for the update!

Nice gradient BTW.
