### ISSUE TITLE
Twitch.tv: Silence speed capped at 2x unless sounded speed >= 2x

### ISSUE THREAD

**Issue by CodeOptimist** [WofWca/jumpcutter#25]
For some reason when sounded speed is below 2x (e.g. 1x, 1.5x), video speed is being capped at 2x during 0dB audio even with a very high silence speed (e.g. 3x, 5x, 10x). Works fine when sounded speed is 2x or higher.

E.g. https://www.twitch.tv/videos/1124147193 at 3:57:30

(I'm using https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk to see the video speed, not the inaccurate one at bottom right of video player.)

**Comment by WofWca** [comment]
We may learn from other extensions:

https://github.com/igrigorik/videospeed/blob/caacb45d614db312cf565e5f92e09a14e52ccf62/inject.js#L467-L472

https://github.com/vantezzen/skip-silence

Could `event.stopImmediatePropagation()` work?

**Comment by WofWca** [comment]
aacc6d5c4
