### ISSUE TITLE
Setting Sounded speed to 0 causes Jump Cutter to stop responding

### ISSUE THREAD

**Issue by zznidar** [WofWca/jumpcutter#30]
When watching a video with Jump Cutter enabled, dragging the _Sounded speed_ slider to 0.00 causes the video to stop playing and the extension popup to stop responding (dragging the sliders has no effect; values stay unchanged).

## Repro steps
1. Play a video with Jump Cutter enabled
2. Open the Jump Cutter popup
3. Drag the _Sounded speed_ slider to the left (0.00)
4. Wait a fraction of a second (to stop debouncing)
5. Video playback stops
6. Drag the _Sounded speed_ slider (or any other slider) to any other value (or click the Enabled checkbox)

## Actual result
Noting happens. All values stay the same. Video playback does not continue.

## Expected result
Jump Cutter should not hang; video should start playing again after dragging the slider (and other sliders and checkboxes should continue working)

## Version
Version: 1.18.1
Firefox 92.0

## Screenshot
Notice how the value of _Sounded speed_ is still 0.00, although the slider has been dragged to a different value.
![image](https://user-images.githubusercontent.com/20877556/135681567-e881c4a6-0e63-4b1c-a26e-f79e21980787.png)

**Comment by WofWca** [comment]
Yeah, should have been more careful implementing custom ranges.
Thanks for reporting.

The workaround is to open a new tab and open the popup, then drag the slider back to normal values.

Will try to fix in a couple of days.

**Comment by WofWca** [comment]
Also c499897
