### ISSUE TITLE
Suggestion: Change badge color scheme or hide if if there is no video

### ISSUE THREAD

**Issue by Hypfer** [WofWca/jumpcutter#33]
I've just installed and tested this extension. It works great!
The only thing I don't like about it is that green badge which is _very_ green.

![image](https://user-images.githubusercontent.com/974410/149359996-a44b963f-cc51-445a-a6b5-b00d54f032e1.png)

Maybe changing the color scheme to match the one seen on the uBlock Origin icon?
Or maybe also hide the badge entirely if there is no video element on the page?

Maybe even both things?

https://github.com/WofWca/jumpcutter/blob/ce5ac8e5b0a2a46d10900f6559724c5ab83264f6/src/background/initIconAndBadgeUpdater.ts#L15-L26

I see that there's a TODO there. What does DRY mean in that context?

**Comment by Hypfer** [comment]
After scrolling a bit further down in that initIconAndBadgeUpdater.ts, I've found `settings.badgeWhatSettingToDisplayByDefault`

![image](https://user-images.githubusercontent.com/974410/149361789-c39f8f58-73dd-46de-8e9a-b247e9f9dec1.png)


Issue solved. The green is still very green though

**Comment by WofWca** [comment]
Feels good to solve issues before they even start existing 😎

DRY means "don't repeat yourself", thought maybe these colors should be the same as the chart colors.

> The green is still very green though

In what sense? Poor contrast? Too bright and distracting?

> so that the simple options such as the badge one come before that huge blob of keyboard hotkeys

Yeah, the options page looks like it could used some work. However I thought that the hotkeys are more important that the badge, therefore they should go first.

**Comment by Hypfer** [comment]
> Too bright and distracting?

Yeah, that one.
For me It's constantly drawing attention even though nothing is happening that would require any.

**Comment by WofWca** [comment]
Manifest V3 adds per-tab badge and icon support. This should be easy to implement now.
