### ISSUE TITLE
Allow higher than 4x Firefox

### ISSUE THREAD

**Issue by sirati** [WofWca/jumpcutter#35]
In the latest Firefox Beta 97.0b9 the cutoff speed for video with audio can be set in about:config and has as a default been [increased to 8x](https://bugzilla.mozilla.org/show_bug.cgi?id=1630569)
I use that version but the plugin currently does not support silent speed >4 and there is no config option for it!

**Comment by WofWca** [comment]
Yeah, I'm preparing a release. Thought it's better to make it when the change goes live (8th of February).
Its gonna automatically detect the version of Firefox.
And for now it would just set it to 8, regardless of what the value of that `about:config` option is.

Thanks.

**Comment by WofWca** [comment]
The update is live on AMO.

The change: 404fc08, the tag: v1.21.3
