### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by comradekingu** [WofWca/jumpcutter#38]
There is no license here or on Weblate.
This seems to be in error(?)

**Comment by WofWca** [comment]
You're right, there's no license yet. I'm thinking of adding one specifically for translations for now. It's gonna be a libre one.
I'm impressed and thankful that there are already people translating it, just after a couple of hours. I guess I'll hide the project on Weblate until it's set up properly to not waste anyone's resources.

By the way, let me know, if you do have a suggestion on what license to choose and how it's best to make it so that it applies to translations only.

**Comment by WofWca** [comment]
I'm gonna do it in a couple of days.

**Comment by comradekingu** [comment]
GPLv3-or-later?
AGPLv3+ is probably not compatible with distribution in the Chrome store.

**Comment by WofWca** [comment]
I thought about GPL. It would automatically force me to apply it to the whole extension as well, as far as I understand. And I have not yet decided if it's the way it should be.
I'm thinking of going for Unlicense or MIT or something like this for now, to maybe change it later.

**Comment by comradekingu** [comment]
If so, what is the problem there?
MIT has some permanent effects, so it isn't good for that. Unlicense is a crayon license that draws in public domain and all sorts of non-achieved ends, but actual problems.

This interpretation sold me on AGPLv3+ https://opensource.google/documentation/reference/using/agpl-policy

**Comment by WofWca** [comment]
Perhaps I'm misunderstanding you? I'm saying that I have not yet decided how I want to license the extension's (not the translations') code, so I'm keeping it "all rights reserved" for now. Using GPL-licensed code (including translations) prohibits this.
What do you think would be a problem with Unlicense?

**Comment by WofWca** [comment]
>I'm thinking of going for Unlicense or MIT or something like this

Also CC0 maybe

**Comment by comradekingu** [comment]
@wofWca CC0 is the worst license there is.
For various different reasons why content doesn't and can't enter the public domain, when worked on in a collaborative fashion, it instead ensures a lot of headache.

**Comment by WofWca** [comment]
Ok, what would you suggest, besides GPL/LGPL?

**Comment by WofWca** [comment]
I have added CC0 for now, but this doesn't mark the end of discussion, it can still be changed.

**Comment by comradekingu** [comment]
I think we can agree BSD-2 does that.

**Comment by WofWca** [comment]
How about LGPLv3-or-later? Would you agree to it?

**Comment by comradekingu** [comment]
Sure. It can be upgraded later on.

**Comment by WofWca** [comment]
046e929db1315d4d2a1c202afdc39b5914e97acf
