### ISSUE TITLE
Disable for some webs option

### ISSUE THREAD

**Issue by PachiMc** [WofWca/jumpcutter#51]
Hi, there should be a whitelist/blacklist for webs because can be bugged in some of them, like twitch

**Comment by WofWca** [comment]
Duplicate of #26.
I'm passively working on it (i.e. learning about optional permissions and stuff, trying to find a good way).

**Comment by WofWca** [comment]
For Twitch there's now this option, which may help

![image](https://user-images.githubusercontent.com/39462442/183078601-4111dc9c-3c99-49d8-b5e3-6c8ebef60f92.png)
