### ISSUE TITLE
fix: sometimes videos start over right as they end on YouTube

### ISSUE THREAD

**Issue by WofWca** [WofWca/jumpcutter#91]
Encountered in Chromium, on YouTube.

This is probably a side effect of desync correction:

https://github.com/WofWca/jumpcutter/blob/0977011707f3a24d2f109adba21bd749a7ed20b0/src/entry-points/content/StretchingController/StretchingController.ts#L350-L374

Yep. As the video ends, if you do a VERY short seek back, it will start over, even without this extension. `$0.currentTime -= 0.001`. Longer seeks (like `1` second) appear to do what they're supposed to do.

I guess we could work around this by checking if the video is near the end / ended.

Same: https://github.com/vantezzen/skip-silence/issues/120

**Comment by Arpit-mohankar** [comment]
hey @WofWca can i work on this issue?

**Comment by WofWca** [comment]
Sure!

**Comment by Arpit-mohankar** [comment]
heyy how can i do this??

**Comment by WofWca** [comment]
As I said, before performing the seek, we need to check whether the video's `currentTime` is close to its `duration`.
I have linked the responsible code in the issue's description.
There's also the same thing in the Cloning controller file.

**Comment by WofWca** [comment]
@Arpit-mohankar Let us know if you're still gonna work on this.

**Comment by Arpit-mohankar** [comment]
@WofWca I am really sorry I'm not able to fix this ☹️

**Comment by WofWca** [comment]
No worries!
