### ISSUE TITLE
fix: in Edge the options page is very narrow

### ISSUE THREAD

**Issue by WofWca** [WofWca/jumpcutter#98]
![image](https://user-images.githubusercontent.com/39462442/182106193-9319c8d9-96fb-4955-ad62-b2ace6c8e213.png)

To prevent it from crunching into a black hole and killing us all, we need to make it wider (and taller)?

**Comment by hychanbn1009** [comment]
I saw some discussion about this issue. But I cannot find any solution to solve this problem.
[https://techcommunity.microsoft.com/t5/discussions/extension-settings-window-is-too-small/m-p/985982](url)

I think one of the alternative solution is to make a Full page options.

Below is an example of Full page options I made in Edge.
![image](https://user-images.githubusercontent.com/51984388/189413453-152a7752-a03e-4950-938b-1d38eed686e5.png)

Doc ref:
[https://developer.chrome.com/docs/extensions/mv3/options/#full_page](url)

**Comment by WofWca** [comment]
Thanks for the link!
I think the solution/workaround is to set `min-width: 700px` (or something like that) on the page itself, in our extension's codebase. Maybe `max-witdth: 0` could work as well.

**Comment by WofWca** [comment]
The full page thing is also ok, we can stick with it until we find a better solution. If someone's willing to implement it, please go ahead.

**Comment by WofWca** [comment]
Alright I've finally published it. To the Microsoft add-ons only, so other stores aren't affected.
